# Generated by Django 3.2.5 on 2021-07-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userdetail_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_name',
            field=models.CharField(default='noimage.png', max_length=50),
        ),
    ]
