# Generated by Django 3.2.5 on 2021-07-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_cart_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='is_seller',
        ),
    ]
